version: '3.8'


services:
  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    container_name: axon-ex
    volumes:
      - axonserver-data:/data
      - axonserver-events:/eventdata
      - axonserver-config:/config:ro
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - docknet

  db:
    image: ${DB_ENGINE}:${DB_ENGINE_VERSION}
    container_name: maria-ex
    hostname: ${DB_ENGINE}
    ports:
      - '3306:3306' # ensure port is not blocked on host machine (host:container)
    volumes:
      - ./axon/config/${DB_ENGINE}/conf:/etc/mysql/conf.d
      - ./axon/data/${DB_ENGINE}:/var/lib/mysql
    user: "1000" # MAC OS hack
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./axon/config/nginx/nginx.conf:/etc/nginx/nginx.conf


  # uncomment running api production, after you have executed ./mvnw package
  #avondock:
  #  image: avondock:0.0.1-SNAPSHOT
  #  container_name: avondock
  #  depends_on:
  #    - db
  #  ports:
  #    - '8098:8098'
  #  environment:
  # Example how you can override application.properties from a docker environment
  #    spring.mail.host: "smpt.example.com"
  #    SPRING_DATASOURCE_1: "jdbc:mariadb://db:3306/avondock?createDatabaseIfNotExist=true"
  #    SPRING_DATASOURCE_2: "jdbc:mariadb://db:3306/system?createDatabaseIfNotExist=true"

  cassandra:
    image: cassandra:3.11.11
    container_name: cass-ex
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - ./axon/data/cassandra:/var/lib/cassandra
    networks:
      - docknet

volumes:
  axonserver-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/axon/data
      o: bind
  axonserver-events:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/axon/events
      o: bind
  axonserver-config:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/axon/config
      o: bind

networks:
  docknet:
